### ISSUE TITLE
Public Mindmaps cause error 500 on NC18+

### ISSUE THREAD

**Issue by MarkPartlett** [ACTom/files_mindmap#104]
I get an error 500 when I open a 'Share link' .

In the nextcloud.log I also get "{"Exception":"TypeError","Message":"substr() expects parameter 3 to be integer, boolean given" 
...
/nextcloud/lib/private/Files/Type/Detection.php","line":377,"function":"substr","args":["mindmap",0,false]}

Verified on multiple environments upgraded to NC18.

**Comment by MarkPartlett** [comment]
The code is looking for a 'mindmap.svg' icon file in nextcloud/core/img/filetypes , once that file exists the link works correctly.

**Comment by thawn** [comment]
I can confirm that:
1) after installing files_mindmap in nextcloud 18, I get an internal server error whenever I try to open a .km file shared via link
2) after downloading `mindmap.svg` into `nextcloud/core/img/filetypes`, the server error is gone. However, bug #101 still appears (i.e. the mindmap appears empty when opend via external shared link)

**Comment by ACTom** [comment]
Reproduce with #99 and #101

**Comment by thawn** [comment]
This issue is not fixed in Mind Map 0.0.21:
## Actual behavior:
I still need to manually copy `mindmap.svg` to `nextcloud/core/img/filetypes` in order to get shared links to work.
This means that after installing Mind Map 0.0.21 in a vanilla nextcloud installation, shared links don't work
Copying `mindmap.svg` to `nextcloud/core/img/filetypes` gives me a warning on the integrity check.
## Expected behavior
sharing links should work out of the box.
The extension should not expect a file that is not part of the standard distribution to exist in `nextcloud/core`
